import { FormEvent, useState } from 'react';
import { money } from '../lib/format';

export function LandingPage({ onLogin, onRegister }: { onLogin: () => void; onRegister: () => void }) {
  const [estimate, setEstimate] = useState<number | null>(null);
  const [excess, setExcess] = useState(5000);
  function calculate(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const value = Number(form.get('assetValue')); const claims = Number(form.get('claims')); const category = String(form.get('assetType'));
    const rates: Record<string, number> = { vehicle: .024, property: .0065, electronics: .038, machinery: .018 };
    setEstimate(Math.max(95, value * (rates[category] ?? .02) * (1 + claims * .18) * Math.max(.7, 1 - (excess - 1000) / 80000) / 12));
  }
  return <div className="landing">
    <header className="landing-nav"><a className="brand brand-dark" href="#top"><span>EI</span><div><strong>EasyInsure</strong><small>Insurance, made clear</small></div></a><nav><a href="#how">How it works</a><a href="#platform">Platform</a><a href="#estimate">Estimate</a><a href="#principles">Our principles</a></nav><div className="landing-actions"><button className="secondary" onClick={onLogin}>Log in</button><button className="primary" onClick={onRegister}>Create account</button></div></header>
    <main id="top">
      <section className="landing-hero"><div className="hero-copy"><span className="landing-kicker"><i /> Built for South African cover</span><h1>Insurance that<br /><em>explains itself.</em></h1><p>Protect what matters, understand what you pay, and move through claims with confidence. AI helps organise the work; people make the decisions.</p><div className="hero-actions"><button className="landing-primary" onClick={onRegister}>Start protecting your assets <span>→</span></button><a href="#estimate">Estimate a premium</a></div><div className="hero-trust"><span>✓ POPIA-minded</span><span>✓ ZAR pricing</span><span>✓ Human approval</span></div></div>
        <div className="hero-product"><div className="product-window"><div className="product-bar"><span><i /><i /><i /></span><small>Secure member workspace</small></div><div className="product-content"><div className="mini-side"><b>EI</b><i /><i /><i /><i /></div><div className="mini-main"><small>PORTFOLIO OVERVIEW</small><h3>Your protection, at a glance.</h3><div className="mini-metrics"><span><b>R 685k</b>Protected value</span><span><b>3</b>Active policies</span><span><b>1</b>Claim in review</span></div><div className="mini-claim"><span>CLM-20381<small>Vehicle damage</small></span><strong>Human review</strong></div><div className="mini-claim"><span>CLM-19804<small>Electronics</small></span><strong className="paid">Approved</strong></div></div></div></div><div className="floating-card"><i>✓</i><span><strong>Decision stays human</strong><small>Every payout needs officer approval</small></span></div></div>
      </section>
      <section className="landing-trust"><span>Built around principles that matter</span><div><strong>Deterministic</strong><strong>Explainable</strong><strong>Auditable</strong><strong>Human-controlled</strong></div></section>
      <section className="landing-section" id="platform"><div className="section-intro"><span className="eyebrow">One connected platform</span><h2>Less insurance admin.<br />More certainty.</h2><p>Everything from registering an asset to understanding a claim outcome belongs in one clear journey.</p></div><div className="feature-cards"><article><span>◇</span><small>01 · ASSETS</small><h3>Know what is protected</h3><p>Build a detailed asset register, connect cover, and keep ownership information current.</p></article><article className="featured"><span>▤</span><small>02 · COVER</small><h3>See the logic behind price</h3><p>Explore valuation, excess and risk factors without black-box calculations.</p></article><article><span>✓</span><small>03 · CLAIMS</small><h3>Follow every decision</h3><p>Submit evidence once, track progress, and see where human review is required.</p></article></div></section>
      <section className="how-section" id="how"><div><span className="eyebrow">How it works</span><h2>A simple path from asset to assurance.</h2></div><ol><li><span>01</span><div><strong>Create your secure profile</strong><p>Tell us who you are and establish your private workspace.</p></div></li><li><span>02</span><div><strong>Register what matters</strong><p>Add the specific details needed for each kind of asset.</p></div></li><li><span>03</span><div><strong>Understand your options</strong><p>Review transparent estimates before choosing cover.</p></div></li><li><span>04</span><div><strong>Manage and claim</strong><p>Keep everything current and follow every claim stage.</p></div></li></ol></section>
      <section className="public-estimator" id="estimate"><div className="estimate-copy"><span className="eyebrow">No login required</span><h2>Start with a ballpark.</h2><p>Use a few simple assumptions to explore an indicative monthly premium. It is a planning tool, not a quote.</p><div><strong>Transparent by default</strong><small>This preview uses fixed category and claims-history factors. No personal data or AI decision-making is involved.</small></div></div><form onSubmit={calculate}><label>What would you like to insure?<select name="assetType"><option value="vehicle">Vehicle</option><option value="property">Property</option><option value="electronics">Electronics</option><option value="machinery">Machinery</option></select></label><label>Approximate replacement value<input name="assetValue" type="number" min="1000" defaultValue="350000" required /></label><label>Claims in the past three years<select name="claims"><option value="0">None</option><option value="1">1 claim</option><option value="2">2 claims</option><option value="3">3 or more</option></select></label><label>Preferred excess <strong>{money.format(excess)}</strong><input type="range" min="1000" max="25000" step="1000" value={excess} onChange={(e) => setExcess(Number(e.target.value))} /></label><button>Calculate ballpark</button>{estimate !== null && <div className="public-result"><span>Indicative monthly premium</span><strong>{money.format(estimate)}</strong><small>Subject to full underwriting and human approval.</small></div>}</form></section>
      <section className="principles-section" id="principles"><span className="eyebrow">A better operating model</span><h2>Technology supports judgment.<br />It does not replace it.</h2><div><article><b>01</b><strong>AI is an assistant</strong><p>It extracts, organises and highlights. Final financial decisions stay with authorized people.</p></article><article><b>02</b><strong>Pricing is deterministic</strong><p>Fixed, versioned formulas keep premiums and depreciation consistent and auditable.</p></article><article><b>03</b><strong>Your data stays yours</strong><p>Personally identifying information is excluded from external AI requests.</p></article></div></section>
      <section className="landing-cta"><div><span>Ready when you are</span><h2>Bring your insurance<br />into focus.</h2></div><button onClick={onRegister}>Create your secure account →</button></section>
    </main>
    <footer className="landing-footer"><div className="brand"><span>EI</span><div><strong>EasyInsure</strong><small>Insurance, made clear</small></div></div><p>© 2026 EasyInsure · South Africa</p><div><a href="#principles">Privacy</a><a href="#principles">Terms</a><button onClick={onLogin}>Member login</button></div></footer>
  </div>;
}
